export const LINKS = [
    ['XiuMi', 'https://xiumi.us/'],
    ['WeiXin', 'https://mp.weixin.qq.com/'],
    ['ECUST', 'https://www.ecust.edu.cn/'],
    ['Node.js', 'https://nodejs.org/'],
    ['NPM', 'https://www.npmjs.com'],
    ['TypeScript', 'https://www.typescriptlang.org/'],
    ['bilibili', 'https://bilibili.com/'],
    ['Vercel', 'https://vercel.com/'],
    ['RuanYifeng', 'https://ruanyifeng.com/blog/'],
    ['localhost:8080', 'http://localhost:8080/'],
    ['localhost:3000', 'http://localhost:3000/'],
    ['localhost:5000', 'http://localhost:5000/'],
    ['GitHub', 'https://github.com/'],
    ['QQMail', 'https://mail.qq.com/'],
    ['QZone', 'https://qzone.qq.com/'],
    ['tuke88', 'http://www.tuke88.com/peiyue/'],
    ['MDN', 'https://developer.mozilla.org/'],
    ['chuangkit', 'https://chuangkit.com/'],
    ['eqxiu', 'https://eqxiu.com/'],
    ['texdoc', 'https://texdoc.org/'],
];
