export const LINKS = [
    ['XiuMi', 'https://xiumi.us/'],
    ['WeiXin', 'https://mp.weixin.qq.com/'],
    ['ECUST', 'https://www.ecust.edu.cn/'],
    ['Node.js', 'https://nodejs.org/'],
    ['NPM', 'https://www.npmjs.com'],
    ['TypeScript', 'https://www.typescriptlang.org/'],
    ['bilibili', 'https://bilibili.com/'],
    ['Vercel', 'https://vercel.com/'],
    ['RuanYifeng', 'https://ruanyifeng.com/blog/'],
    ['localhost:8080', 'http://localhost:8080/'],
    ['localhost:3000', 'http://localhost:3000/'],
    ['GitHub', 'https://github.com/'],
    ['QQMail', 'https://mail.qq.com/'],
];
